#!/usr/bin/perl -w
use strict;

my $name = undef;
my $number = undef;

sub parse_changelog() {
    open(CHANGELOG, "-|", "dpkg-parsechangelog") or exit 1;
    while (<CHANGELOG>) {
	$name = $1 if /^Source:\s+(\S+)/;
	$number = $1 if /^Version:\s+(\S+)/;
    }
    close(CHANGELOG);
    defined $name or die "$0: package name not found in changelog\n";
    defined $number or die "$0: version number not found in changelog\n";
}

sub write_version() {
    print <<EOF;
let name = "$name"
let number = "$number"
EOF
}

parse_changelog();
write_version();
