.\" approx: proxy server for Debian archive files
.\" Copyright (C) 2005  Eric C. Cooper <ecc@cmu.edu>
.\" Released under the GNU General Public License
.\" -*- nroff -*-
.TH APPROX 8 "September 2006"
.\" Please adjust this date whenever revising the manpage.

.SH NAME
approx \- proxy server for Debian archive files

.SH SYNOPSIS
.PP
.B approx
[\fIOPTION\fP]...

.SH DESCRIPTION
.B approx
listens for HTTP requests made by
.BR apt\-get (8).
It maintains a cache of Debian archive files that have been previously
downloaded, so that it can respond with a local copy when possible.
If a file not in the cache is requested,
.B approx
will download it from a remote Debian repository and deliver the
contents to the client, simultaneously caching it for future use.

Over time, the
.B approx
server cache will grow to contain multiple, unneeded versions of
Debian packages.  The
.BR gc_approx (8)
program removes these from the cache.

.SH OPTIONS
.TP
.BR \-f ", " \-\^\-foreground
Run in the foreground instead of detaching as a daemon,
and print messages to standard error instead of the system log.
.TP
.BR \-v ", " \-\^\-version
Display
.B approx
version information and exit.

.SH EXAMPLES
By default,
.B approx
listens on port 9999 (for compatibility with
.BR apt\-proxy (8)).
Suppose that a client machine's
.I /etc/apt/sources.list
file contains the following lines:
.IP
deb     http://apt:9999/debian    testing main
.br
deb     http://apt:9999/security  testing/updates main
.br
deb-src http://apt:9999/debian    unstable main
.PP
In this example,
.I apt
is the hostname of the
.B approx
server machine on the local network.
Each distribution, such as "debian" or "security", is mapped
to a remote repository in the
.B approx
server's configuration file.
.PP
For example, the
.I approx.conf
file on the
.B approx
server might contain the lines
.IP
debian   http://ftp.debian.org/debian
.br
security http://security.debian.org

.SH FILES
.TP
.I /etc/approx/approx.conf
.br
Configuration file for
.B approx
and
.BR gc_approx .
.TP
.I /var/cache/approx
.br
Cache directory for archive files.

.SH SEE ALSO
.IR approx.conf (5),
.BR gc_approx (8),
.BR apt\-get (8),
.IR sources.list (5)

.SH AUTHOR
Eric Cooper <ecc@cmu.edu>
