.\" approx: proxy server for Debian archive files
.\" Copyright (C) 2012  Eric C. Cooper <ecc@cmu.edu>
.\" Released under the GNU General Public License
.\" -*- nroff -*-
.TH APPROX.CONF 5 "Apr 2012"
.\" Please adjust this date when revising the manpage.

.SH NAME
approx.conf \- configuration file for approx proxy server

.SH SYNOPSIS
.PP
/etc/approx/approx.conf

.SH DESCRIPTION
.PP
Each non-blank line of the configuration file should contain
a name/value pair, separated by white space.
Comments start with a "#" character and continue to the end of the line.
.PP
Names that begin with the "$" character are reserved for use as
configuration parameters.  The following parameters are currently defined:
.IP $cache
Specifies the location of the approx cache directory
(default:
.IR /var/cache/approx ).
It and all its subdirectories must be owned by the approx server
(see also the $user and $group parameters, below.)
.IP $interval
Specifies the time in minutes after which a cached file will be
considered too old to deliver without first checking with the remote
repository for a newer version (default: 60)
.IP $max_rate
Specifies the maximum download rate from remote repositories,
in bytes per second (default: unlimited).
The value may be suffixed with "K", "M", or "G"
to indicate kilobytes, megabytes, or gigabytes per second, respectively.
.IP $max_redirects
Specifies the maximum number of HTTP redirections that will be followed
when downloading a remote file (default: 5)
.IP "$user, $group"
Specifies the user and group that
owns the files in the approx cache (default: approx)
.IP $syslog
Specifies the
.BR syslog (3)
facility to use when logging (default: daemon)
.IP $pdiffs
Specifies whether to support IndexFile diffs
(default:
.BR true )
.IP $offline
Specifies whether to deliver (possibly out-of-date) cached files when
they cannot be downloaded from remote repositories
(default:
.BR false )
.IP $max_wait
Specifies how many seconds an
.BR approx (8)
process will wait for a concurrent download of a file to complete,
before attempting to download the file itself (default: 10)
.IP $curl_path
Specifies the path to the curl binary (default:
.IR /usr/bin/curl )
.IP $verbose
Specifies whether informational messages should be printed in the log
(default:
.BR false )
.IP $debug
Specifies whether debugging messages should be printed in the log
(default:
.BR false )
.PP
The other name/value pairs  are used to map distribution names
to remote repositories.  For example,
.IP
debian          http://ftp.debian.org/debian
.br
security        http://security.debian.org
.SH TCP PORT NUMBER
.PP
The port on which
.BR approx (8)
listens is not specified in this file, but in
.IR /etc/inetd.conf .
The default value is 9999, for compatibility with
.BR apt\-proxy (8),
but it may be changed by running the command
.IP
dpkg-reconfigure approx
.SH SEE ALSO
.BR approx (8),
.BR approx-gc (8),
.BR inetd (8)

.SH AUTHOR
Eric Cooper <ecc@cmu.edu>
