.\" approx: proxy server for Debian archive files
.\" Copyright (C) 2008  Eric C. Cooper <ecc@cmu.edu>
.\" Released under the GNU General Public License
.\" -*- nroff -*-
.TH APPROX.CONF 5 "March 2008"
.\" Please adjust this date when revising the manpage.

.SH NAME
approx.conf \- configuration file for approx proxy server

.SH SYNOPSIS
.PP
/etc/approx/approx.conf

.SH DESCRIPTION
.PP
Each non-blank line of the configuration file should contain
a name/value pair, separated by white space.
Comments start with a "#" character and continue to the end of the line.
.PP
Names that begin with the "$" character are reserved for use as
configuration parameters.  The following parameters are currently defined:
.IP $interface
Specifies the name of the network interface on which the
.BR approx (8)
server listens for HTTP requests (default: any)
.IP $port
Specifies the TCP port on which the
.BR approx (8)
server listens for HTTP requests (default: 9999)
.IP $max_rate
Specifies the maximum download rate from remote repositories,
in bytes per second (default: unlimited).
The value may be suffixed with "K", "M", or "G"
to indicate kilobytes, megabytes, or gigabytes per second, respectively.
.IP $max_redirects
Specifies the maximum number of HTTP redirections that will be followed
when downloading a remote file (default: 5)
.IP "$user, $group"
Specifies the name of the user and group to use after the daemon drops
privileges (default: approx)
.IP $syslog
Specifies the
.BR syslog (3)
facility to use when logging (default: daemon)
.IP $pdiffs
Specifies whether to support IndexFile diffs
(default:
.BR true )
.IP $offline
Specifies whether to deliver (possibly out-of-date) cached files when
they cannot be downloaded from remote repositories
(default:
.BR false )
.IP $max_wait
Specifies how many seconds an
.BR approx (8)
process will wait for a concurrent download of a file to complete,
before attempting to download the file itself (default: 10)
.IP $verbose
Specifies whether informational messages should be printed in the log
(default:
.BR false )
.IP $debug
Specifies whether debugging messages should be printed in the log
(default:
.BR false )
.PP
The other name/value pairs  are used to map distribution names
to remote repositories.  For example,
.IP
debian          http://ftp.debian.org/debian
.br
security        http://security.debian.org/debian-security
.SH SEE ALSO
.BR approx (8),
.BR gc_approx (8)

.SH AUTHOR
Eric Cooper <ecc@cmu.edu>
