.\" approx: proxy server for Debian archive files
.\" Copyright (C) 2006  Eric C. Cooper <ecc@cmu.edu>
.\" Released under the GNU General Public License
.\" -*- nroff -*-
.TH GC_APPROX 8 "November 2007"
.\" Please adjust this date whenever revising the manpage.

.SH NAME
gc_approx \- garbage-collect the cache of Debian archive files

.SH SYNOPSIS
.PP
.B gc_approx
[\fIOPTION\fP]...

.SH DESCRIPTION
.PP
.B gc_approx
scans the cache created by
.BR approx (8)
and finds files that are corrupted or no longer needed.
With no options specified, these files
are listed on standard output and removed from the cache.
.PP
A corrupted file is one whose size or checksum
does not match the value specified in the
.I Packages
or
.I Sources
file.
.PP
An unneeded file is one that is not referenced from any distribution's
.I Packages
or
.I Sources
file.
.PP
.B gc_approx
may take several minutes to finish.

.SH OPTIONS
.TP
.BR \-f ", " \-\^\-fast
Don't perform checksum validation.
.TP
.BR \-k ", " \-\^\-keep ", " \-s ", " \-\^\-simulate
Don't remove files from the cache.
.TP
.BR \-q ", " \-\^\-quiet
Don't print file names.
.TP
.BR \-v ", " \-\^\-verbose
Indicate the reason for removal of each file with a prefix character:
\`=\' for incorrect size, \`!\' for incorrect checksum, blank for unneeded.

.SH EXAMPLES
.PP
To remove all unneeded or corrupted files from the cache:
.IP
gc_approx \-\^\-quiet
.PP
This is run as a weekly
.BR cron (8)
job.
.PP
To list the files that would be removed from the cache,
without actually doing so:
.IP
gc_approx \-\^\-keep

.SH FILES
.TP
.I /etc/approx/approx.conf
.br
Configuration file for
.B approx
and related programs.
.TP
.I /var/cache/approx
.br
Cache directory for archive files.

.SH SEE ALSO
.IR approx.conf (5),
.BR approx (8),
.BR update_approx (8),
.BR cron (8)

.SH AUTHOR
Eric Cooper <ecc@cmu.edu>
